version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.12.8-management

  aggregatorcompany.api:
    image: ${DOCKER_REGISTRY-}aggregatorcompanyapi
    build:
      context: .
      dockerfile: AggregatorCompany/AggregatorCompany.API/Dockerfile

  flightcompany.api:
    image: ${DOCKER_REGISTRY-}flightcompanyapi
    build:
      context: .
      dockerfile: FlightCompany/FlightCompany.Api/Dockerfile


  hotelcompany.api:
    image: ${DOCKER_REGISTRY-}hotelcompanyapi
    build:
      context: .
      dockerfile: HotelCompany/HotelCompany.Api/Dockerfile


  paymentcompany.api:
    image: ${DOCKER_REGISTRY-}paymentcompanyapi
    build:
      context: .
      dockerfile: PaymentCompany/PaymentCompany.Api/Dockerfile

